tap "homebrew/bundle"

brew "fzf"
brew "go"
brew "helm"
brew "kubectx"
brew "node"
brew "ripgrep"
brew "tmux"

cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-hasklug-nerd-font"
cask "iterm2"
cask "visual-studio-code"
