#!/usr/bin/env bash

# Set directory
export DOTFILES=${1:-"$HOME/.dotfiles"}
cd "$DOTFILES" || exit

local desired=$(<vscode/extensions.txt)
local current=$(code --list-extensions)

for extension in "${desired[@]}"; do
  if echo "$current" | grep -qi "^$extension$"; then
    echo "$extension is already installed. Skipping..."
  else
    echo "Installing $extension..."
    code --install-extension "$extension"
  fi
done

cd -
